name: SDK Info

on:
  workflow_dispatch:

jobs:
  sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Show release files
        run: |
          wget -qO- https://downloads.openwrt.org/releases/25.12.4/targets/mediatek/filogic/ | grep sdk || true
          wget -qO- https://downloads.openwrt.org/releases/25.12.4/targets/mediatek/filogic/ | grep toolchain || true
